name: Build and release pre-built binaries (Dev build)

on:
  push:
    branches:
      - main

jobs:
  pre-release:
    name: Create Github Release
    needs: [build]
    runs-on: ubuntu-20.04
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        name: Create Release
        id: create_release
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest Development Release"
